name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

  deliverit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: mr-smithers-excllent/docker-build-push@v6
        with:
          image: Dockerized-Laravel-Authn.-App/Laravel-Auth-App # Corrected Docker image name
          registry: docker.io
          dockerfile: Dockerfile
          username: "${{ secrets.hub_email }}"
          password: "${{ secrets.hub_password }}"
          tags: latest

    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
